title: morpheus

tagline: <a href="https://learn.athleanx.com/articles/how-to-do-skullcrushers-correctly">skull crusher</a>, <a href="https://en.wikipedia.org/wiki/Internet_culture">digitally</a>, <a href="https://en.wikipedia.org/wiki/Epistemology">epistomologically</a> & metaphorically speaking of course
author: Morpheus
description: >-
  <a href="https://en.wikipedia.org/wiki/Big_Bang">Bang</a> <a href="https://en.wikipedia.org/wiki/Universe">Universe</a> <a href="https://en.wikipedia.org/wiki/Sun">Sun</a> <a href="https://en.wikipedia.org/wiki/Age_of_Enlightenment">Illuminati</a> <a href="https://en.wikipedia.org/wiki/Memento_mori">Memento Mori</a> <a href="https://en.wikipedia.org/wiki/Chaos_theory">Chaos Theory</a> <a href="https://en.wikipedia.org/wiki/Monte_Carlo_method">Monte Carlo</a>

creed:
 - Ars longa, vita brevis, occasio praeceps, experimentum periculosum, iudicium difficile.

 - Every man must decide whether he will walk in the light of creative altruism or in the darkness of destructive selfishness. - Martin Luther King Jr.

 - Optimism is the faith that leads to achievement. Nothing can be done without hope and confidence. - Helen Keller

 - Do not go where the path may lead, go instead where there is no path and leave a trail. - Ralph Waldo Emerson

 - Morpheus — Μορφεύς. God of dreams, who appears to sleepers in human form. Best known from Ovid’s Metamorphoses.

 - Khufu (also known as Cheops) was the second pharaoh of Egypt’s Fourth Dynasty and the builder of the Great Pyramid of Giza. He reigned during the 26th century BC (early Old Kingdom period) and succeeded his father, Sneferu. 

 - the anthropological approach, the anthropomorphical approach, the zoomorphic approach, the symbolic approach, the philosophical approach,  the linguistical approach, the semantical approach, the <a href="https://en.wikipedia.org/wiki/Xenophobia">artistic</a> approach, the spiritual approach, and the morphological approach. - morpheus(mk ultra m6 ultra pro, premium, premium)

 - There are two kinds of people, those who do the work and those who take the credit. Try to be in the first group; there is less competition there.  - Indira Gandhi

 - <a href="https://buymeacoffee.com/morpheusk">Buy me a cup of coffee</a>

# baseurl: "" # the subpath of your site, e.g. /blog
domain: morphykuffour.github.io
url: https://morphykuffour.github.io
github_username: morph-k

resume_pdf: https://morph-k.github.io/resume/resume.pdf
resume_source: https://github.com/morph-k/resume

favicon: /images/avatar.png

remote_theme: riggraz/no-style-please

theme_config:
  appearance: "auto" # can be "light", "dark" or "auto"
  back_home_text: ".." # customize text for homepage link
  date_format: "%Y-%m-%d"
  show_description: true # show blog description in homepage
  show_lastmod: false
  show_categories: true
  lowercase_titles: false

sass:
  style: compressed

plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-seo-tag

exclude:
  - images/watercrown/sheet.jpg
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
