title: morpheus
author: Morphy Kuffour
description: >-
  nixos, arch, security, qmk, zmk, vim, emacs, neovim, scripting, keyboards, programming
# baseurl: "" # the subpath of your site, e.g. /blog
domain: morphykuffour.github.io
url: https://morphykuffour.github.io
github_username: morphykuffour

remote_theme: riggraz/no-style-please

theme_config:
  appearance: "auto" # can be "light", "dark" or "auto"
  back_home_text: ".." # customize text for homepage link
  date_format: "%Y-%m-%d"
  show_description: true # show blog description in homepage
  show_lastmod: false
  show_categories: true
  lowercase_titles: false

sass:
  style: compressed

plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-seo-tag
